services:
  learningplatformcloud:
    image: ladyred/learningplatformcloud:latest
    container_name: learningplatformcloud

    ports:
      - "8081:8080"

    env_file:
      - .env

    volumes:
      - /home/natalia/oracle-wallets/semana1:/app/wallet:ro

    restart: "no"